version = "6.6"
dependencies = []
build_dependencies = []

[script_args]
unpack_directory = "ncurses-6.6"

[source]
url = "https://invisible-mirror.net/archives/ncurses/ncurses-6.6.tar.gz"
checksum = "355b4cbbed880b0381a04c46617b7656e362585d52e9cf84a67e2009b749ff11"

[targets.linux]

[targets.mac]
skip_symlinking = true
