version    = "2.72"
dependencies = ["m4"]
build_dependencies = []

[script_args]
unpack_directory = "autoconf-2.72"

# Linux aarch64 (ARM64)
[targets.aarch64-unknown-linux-gnu]
url       = "http://ftpmirror.gnu.org/gnu/autoconf/autoconf-2.72.tar.gz"
dependencies = ["perl"]

# macOS Intel
[targets.x86_64-apple-darwin]
url       = "http://ftpmirror.gnu.org/gnu/autoconf/autoconf-2.72.tar.gz"
# perl is provided by macos

# macOS ARM (Apple Silicon)
[targets.aarch64-apple-darwin]
url       = "http://ftpmirror.gnu.org/gnu/autoconf/autoconf-2.72.tar.gz"
# perl is provided by macos
