version    = "3.4.1"
dependencies = ["ncurses@>6.0"]
build_dependencies = ["autoconf", "automake", "libtool"]

[script_args]
unpack_directory = "htop-3.4.1"

# Linux aarch64 (ARM64)
[targets.aarch64-unknown-linux-gnu]
url       = "https://github.com/htop-dev/htop/archive/refs/tags/3.4.1.tar.gz"
checksum  = "904f7d4580fc11cffc7e0f06895a4789e0c1c054435752c151e812fead9f6220"

# macOS Intel
[targets.x86_64-apple-darwin]
url       = "https://github.com/htop-dev/htop/archive/refs/tags/3.4.1.tar.gz"
checksum  = "904f7d4580fc11cffc7e0f06895a4789e0c1c054435752c151e812fead9f6220"

# macOS ARM (Apple Silicon)
[targets.aarch64-apple-darwin]
url       = "https://github.com/htop-dev/htop/archive/refs/tags/3.4.1.tar.gz"
checksum  = "904f7d4580fc11cffc7e0f06895a4789e0c1c054435752c151e812fead9f6220" 